export const studySpacesCopy = {
  fr: {
    title: "Tes espaces d’étude", subtitle: "Retrouve ceux qui étudient les mêmes sujets.", yours: "Tes espaces", discover: "À découvrir",
    search: "Université, domaine, programme, cours…", create: "Créer un espace", join: "Rejoindre", leave: "Quitter", joined: "Membre",
    university: "Université", field: "Domaine", program: "Programme", course: "Cours", exam: "Examen", hub: "Tous les étudiants",
    discussion: "Discussion", question: "Question", resource: "Ressource", all: "Tout", members: "membres", member: "membre",
    recent: "publications récentes", fresh: "Nouvel espace", back: "Tous mes espaces", close: "Fermer", publish: "Publier", newPost: "Publier dans cet espace",
    compose: "Une question, une idée, quelque chose à partager ?", reply: "Répondre", replies: "réponses", send: "Envoyer", cancel: "Annuler",
    wider: "Élargis la conversation", quiet: "Cet espace démarre. Tu peux aussi retrouver des étudiants dans les espaces plus larges.",
    activeWider: "La discussion continue aussi ici", noPosts: "Le début d’une conversation", noPostsBody: "Pose ta première question ou partage une ressource. Les espaces plus larges restent à portée de main.",
    noResults: "Aucun espace trouvé", noResultsBody: "Cherche un autre nom, ou crée l’espace pour ton cours ou ton établissement.",
    noMembership: "Ton parcours, tes espaces", noMembershipBody: "Renseigne tes études ou rejoins un espace pour le retrouver ici.",
    profile: "Compléter mes études", profileHint: "Ajoute ton domaine pour trouver les étudiants qui travaillent sur les mêmes sujets.",
    name: "Nom de l’espace", parent: "Dans quel espace ?", parentHint: "Le cours est lié à une université. Un examen est lié à un cours.",
    publicHint: "Cet espace, ses membres et ses publications sont visibles par les étudiants connectés. Pour un échange privé, utilise Friends.",
    demo: "Aperçu · données de démonstration",
    postActions: "Actions de la publication", noFilteredPosts: "Aucune publication de type « {type} »", noFilteredPostsBody: "Les autres échanges restent dans le fil principal.", showAll: "Voir toutes les publications",
    syncError: "Tes espaces restent accessibles, mais tes dernières informations d’études n’ont pas pu être synchronisées. Vérifie ton profil.",
    date: "Date de l’examen (facultatif)", createHint: "Les espaces existants sont réutilisés automatiquement.",
    universityHint: "Cherche dans l’annuaire mondial ou saisis ton établissement.", courseHint: "Code et nom du cours, par exemple ADV3008", examHint: "Nom et session, par exemple Exam 2 · Fall 2026",
    error: "Impossible de charger les espaces. Réessaie dans un instant.", retry: "Réessayer", saveError: "Impossible d’enregistrer. Ton texte est conservé.",
    attachment: "Joindre un fichier", openAttachment: "Ouvrir la pièce jointe", loadMore: "Publications précédentes", loading: "Chargement…",
    readOnly: "Rejoins cet espace pour participer.", delete: "Supprimer", deleteConfirm: "Supprimer cette publication et ses réponses ?",
    addPlanning: "Ajouter au planning", addedPlanning: "Ajouté au planning", thread: "Conversation", noReplies: "Sois le premier à répondre.",
    children: "Dans cet espace", untitled: "Pièce jointe", fieldRequired: "Choisis un domaine.", parentRequired: "Choisis un espace parent compatible.",
    spacesUnavailable: "Les espaces ne sont pas encore disponibles. Tes anciens contenus sont conservés.", moreSearch: "Affiner la recherche", removeFile: "Retirer le fichier",
    createShort: "Créer", results: "Résultats", hubContext: "Toutes les universités", global: "Toutes les universités", path: "Emplacement de l’espace",
    student: "étudiant", students: "étudiants", filters: "Filtrer les publications", postKind: "Type de publication",
    leaveSpace: "Quitter l’espace",
    reasonCourses: "Lié à tes cours", reasonField: "Lié à ton domaine", reasonFieldElsewhere: "Ton domaine à {uni}",
    reasonInside: "Dans {parent}", reasonPopularAt: "Actif à {uni}", reasonAt: "À {uni}",
    reasonActive: "{n} publications récentes", reasonActiveOne: "1 publication récente", reasonGlobal: "Ouvert à toutes les universités",
    widenQuiet: "Pas encore grand-chose ici ? Continue dans", widenActive: "La conversation continue dans",
    createKind: "Quel espace crées-tu ?",
    universityDescribe: "Ton établissement", fieldDescribe: "Un grand domaine dans une université",
    programDescribe: "Un diplôme ou une filière précise", courseDescribe: "Un cours, avec son code",
    examDescribe: "Une session d’examen d’un cours",
    existsAlready: "Cet espace existe déjà. Tu vas le rejoindre plutôt que d’en créer un second.",
    similarSpaces: "Des espaces proches existent déjà :", joinExisting: "Rejoindre l’espace existant",
  },
  en: {
    title: "Your study spaces", subtitle: "Find people working on the same subjects.", yours: "Your spaces", discover: "Discover",
    search: "University, field, program, course…", create: "Create a space", join: "Join", leave: "Leave", joined: "Member",
    university: "University", field: "Field", program: "Program", course: "Course", exam: "Exam", hub: "All students",
    discussion: "Discussion", question: "Question", resource: "Resource", all: "All", members: "members", member: "member",
    recent: "recent posts", fresh: "New space", back: "All my spaces", close: "Close", publish: "Publish", newPost: "Post in this space",
    compose: "A question, an idea, something to share?", reply: "Reply", replies: "replies", send: "Send", cancel: "Cancel",
    wider: "Widen the conversation", quiet: "This space is just getting started. You can also meet students in the broader spaces.",
    activeWider: "The conversation continues here too", noPosts: "The start of a conversation", noPostsBody: "Ask the first question or share a resource. Broader spaces are always within reach.",
    noResults: "No spaces found", noResultsBody: "Try another name, or create a space for your course or university.",
    noMembership: "Your studies, your spaces", noMembershipBody: "Add your study details or join a space to find it here.",
    profile: "Complete my study details", profileHint: "Add your field to find people working on the same subjects.",
    name: "Space name", parent: "Inside which space?", parentHint: "A course belongs to a university. An exam belongs to a course.",
    publicHint: "This space, its members and its posts are visible to signed-in students. Use Friends for private conversations.",
    demo: "Preview · demonstration data",
    postActions: "Post actions", noFilteredPosts: "No {type} posts yet", noFilteredPostsBody: "Other conversations are still available in the main timeline.", showAll: "View all posts",
    syncError: "Your spaces are still available, but your latest study details could not be synced. Check your profile.",
    date: "Exam date (optional)", createHint: "Existing spaces are reused automatically.",
    universityHint: "Search the worldwide directory or enter your institution.", courseHint: "Course code and name, for example ADV3008", examHint: "Name and term, for example Exam 2 · Fall 2026",
    error: "Could not load spaces. Please try again.", retry: "Try again", saveError: "Could not save. Your text has been kept.",
    attachment: "Attach a file", openAttachment: "Open attachment", loadMore: "Older posts", loading: "Loading…",
    readOnly: "Join this space to take part.", delete: "Delete", deleteConfirm: "Delete this post and its replies?",
    addPlanning: "Add to planning", addedPlanning: "Added to planning", thread: "Conversation", noReplies: "Be the first to reply.",
    children: "Inside this space", untitled: "Attachment", fieldRequired: "Choose a field.", parentRequired: "Choose a compatible parent space.",
    spacesUnavailable: "Study spaces are not available yet. Your existing posts are safe.", moreSearch: "Refine your search", removeFile: "Remove file",
    createShort: "Create", results: "Results", hubContext: "Every university", global: "Every university", path: "Where this space sits",
    student: "student", students: "students", filters: "Filter posts", postKind: "Post type",
    leaveSpace: "Leave space",
    reasonCourses: "Related to your courses", reasonField: "Related to your field", reasonFieldElsewhere: "Your field at {uni}",
    reasonInside: "Inside {parent}", reasonPopularAt: "Active at {uni}", reasonAt: "At {uni}",
    reasonActive: "{n} recent posts", reasonActiveOne: "1 recent post", reasonGlobal: "Open to every university",
    widenQuiet: "Not much here yet? Continue in", widenActive: "The conversation continues in",
    createKind: "What are you creating?",
    universityDescribe: "Your institution", fieldDescribe: "A broad field within a university",
    programDescribe: "A specific degree or track", courseDescribe: "A course, with its code",
    examDescribe: "An exam session for a course",
    existsAlready: "This space already exists. You will join it instead of creating a second one.",
    similarSpaces: "Similar spaces already exist:", joinExisting: "Join the existing space",
  },
};
